# Imagen base de Node.js
FROM node:18

# Establecer directorio de trabajo
WORKDIR /usr/src/app

# Copiar archivos del proyecto
COPY package*.json ./
RUN npm install

# Copiar el código de la API
COPY . .

# Exponer el puerto
EXPOSE 3002

# Comando de inicio
CMD ["node", "index.js"]
